# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2738e2d25409ac8b7c397a9a4382d891883e34e0a89d7bba69588f111766ba9de7d58e063056db84427b730eed7831177a3bc179b352b26bfe31b51ef486878c

test:
  secret_key_base: 1d5fb062d190f519e47f4f4b66c7e825bcfce2b80305cb7d7065e706cec2cf8b8e86eff2b48c1fe631e0e8f93908f7bab93e5ba8fd971ecca4350c99dec23409

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
